server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/pokedex_users?createDatabaseIfNotExist=true
    username: root
    password: javajava
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: super-contra-secreta-clave-muy-segura-123456